# Copyright 2018-2024 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes the New Relic Agent and configures it to connect to the service"
  homepage = "https://github.com/paketo-buildpacks/new-relic"
  id = "paketo-buildpacks/new-relic"
  keywords = ["new-relic", "agent", "apm", "java", "node.js", "php", "python", "dotnet"]
  name = "Paketo Buildpack for New Relic"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/new-relic/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/amd64/bin/helper", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "linux/arm64/bin/helper", "buildpack.toml", "resources/newrelic.js", "resources/newrelic.yml", "resources/newrelic.ini"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    description = "the SHA256 hash of the New Relic extensions archive"
    name = "BP_NEW_RELIC_EXT_SHA256"

  [[metadata.configurations]]
    build = true
    default = "0"
    description = "the number of directory components to strip from the New Relic extensions archive"
    name = "BP_NEW_RELIC_EXT_STRIP"

  [[metadata.configurations]]
    build = true
    description = "the download location of the New Relic extensions"
    name = "BP_NEW_RELIC_EXT_URI"

  [[metadata.configurations]]
    build = true
    description = "the version of the New Relic extensions"
    name = "BP_NEW_RELIC_EXT_VERSION"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:newrelic:java-agent:8.13.0:*:*:*:*:*:*:*"]
    id = "new-relic-java"
    name = "New Relic Java Agent"
    purl = "pkg:generic/newrelic-java-agent@8.13.0"
    sha256 = "1b612bc188161d726597ffe744db1ad6cefedbfe0fbfb4cfa2d408cfcaee21e9"
    source = "https://repo1.maven.org/maven2/com/newrelic/agent/java/newrelic-agent/8.13.0/newrelic-agent-8.13.0-sources.jar"
    source-sha256 = "0deb91d3c226803454f3c6e6a19391d37ca6c585236a9adf13ab8ac0ce846168"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/newrelic/agent/java/newrelic-agent/8.13.0/newrelic-agent-8.13.0.jar"
    version = "8.13.0"

    [[metadata.dependencies.licenses]]
      uri = "https://newrelic.com/docs/java/java-agent-license"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:newrelic:nodejs-agent:12.2.0:*:*:*:*:*:*:*"]
    id = "new-relic-nodejs"
    name = "New Relic NodeJS Agent"
    purl = "pkg:generic/newrelic-nodejs-agent@12.2.0?arch=amd64"
    sha256 = "65c9a5a8d8698cc496e78e4f010e84687d739b1c0b41d80b19a1de700bc1f900"
    source = "https://registry.npmjs.org/newrelic/-/newrelic-12.2.0.tgz"
    source-sha256 = "65c9a5a8d8698cc496e78e4f010e84687d739b1c0b41d80b19a1de700bc1f900"
    stacks = ["*"]
    uri = "https://registry.npmjs.org/newrelic/-/newrelic-12.2.0.tgz"
    version = "12.2.0"

    [[metadata.dependencies.licenses]]
      uri = "https://github.com/newrelic/node-newrelic/blob/HEAD/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:appdynamics:php-agent:11.0.0:*:*:*:*:*:*:*"]
    id = "new-relic-php"
    name = "New Relic PHP Agent"
    purl = "pkg:generic/newrelic-php-agent@11.0.0?arch=amd64"
    sha256 = "314b6f7540a9aac5c8ee4031a959a73cda0fd51abd40231c203578af036b60e7"
    source = "https://github.com/newrelic/newrelic-php-agent/archive/refs/tags/v11.0.0.13.tar.gz"
    source-sha256 = "69f72541acf03e63a4d7d4a1053857b009279d1c526c9b68ed1338670a9e2cc0"
    stacks = ["*"]
    uri = "https://download.newrelic.com/php_agent/archive/11.0.0.13/newrelic-php5-11.0.0.13-linux.tar.gz"
    version = "11.0.0"

    [[metadata.dependencies.licenses]]
      uri = "https://docs.newrelic.com/docs/licenses/license-information"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:appdynamics:dotnet-agent:10.28.0:*:*:*:*:*:*:*"]
    id = "new-relic-dotnet"
    name = "New Relic Dotnet Agent"
    purl = "pkg:generic/newrelic-dotnet-agent@10.28.0?arch=amd64"
    sha256 = "8aeb38a6d6332c62542b80752a233469dafb556f4f98df90a6f0121978e61509"
    source = "https://github.com/newrelic/newrelic-dotnet-agent/archive/refs/tags/v10.28.0.tar.gz"
    source-sha256 = "ae58221f24a73254cb29dc3f9eb939e97ac77f72ddd982a848ead4559f2eed97"
    stacks = ["*"]
    uri = "https://download.newrelic.com/dot_net_agent/previous_releases/10.28.0/newrelic-dotnet-agent_10.28.0_amd64.tar.gz"
    version = "10.28.0"

    [[metadata.dependencies.licenses]]
      uri = "https://docs.newrelic.com/docs/licenses/license-information"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
