# Copyright 2018-2024 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes the New Relic Agent and configures it to connect to the service"
  homepage = "https://github.com/paketo-buildpacks/new-relic"
  id = "paketo-buildpacks/new-relic"
  keywords = ["new-relic", "agent", "apm", "java", "node.js", "php", "python", "dotnet"]
  name = "Paketo Buildpack for New Relic"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/new-relic/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/amd64/bin/helper", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "linux/arm64/bin/helper", "buildpack.toml", "resources/newrelic.js", "resources/newrelic.yml", "resources/newrelic.ini"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    description = "the SHA256 hash of the New Relic extensions archive"
    name = "BP_NEW_RELIC_EXT_SHA256"

  [[metadata.configurations]]
    build = true
    default = "0"
    description = "the number of directory components to strip from the New Relic extensions archive"
    name = "BP_NEW_RELIC_EXT_STRIP"

  [[metadata.configurations]]
    build = true
    description = "the download location of the New Relic extensions"
    name = "BP_NEW_RELIC_EXT_URI"

  [[metadata.configurations]]
    build = true
    description = "the version of the New Relic extensions"
    name = "BP_NEW_RELIC_EXT_VERSION"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:newrelic:java-agent:8.15.0:*:*:*:*:*:*:*"]
    id = "new-relic-java"
    name = "New Relic Java Agent"
    purl = "pkg:generic/newrelic-java-agent@8.15.0"
    sha256 = "aacb466c39fb64a81efb4fd074681680f268509d32360c41918e0faad8e91a75"
    source = "https://repo1.maven.org/maven2/com/newrelic/agent/java/newrelic-agent/8.15.0/newrelic-agent-8.15.0-sources.jar"
    source-sha256 = "f92e40530436c71ebeda249342a30fafcd7d8cd7ec663decf9980a1112234369"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/newrelic/agent/java/newrelic-agent/8.15.0/newrelic-agent-8.15.0.jar"
    version = "8.15.0"

    [[metadata.dependencies.licenses]]
      uri = "https://newrelic.com/docs/java/java-agent-license"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:newrelic:nodejs-agent:12.5.0:*:*:*:*:*:*:*"]
    id = "new-relic-nodejs"
    name = "New Relic NodeJS Agent"
    purl = "pkg:generic/newrelic-nodejs-agent@12.5.0?arch=amd64"
    sha256 = "2a677c95ce634dccae627ee8dc06a30b106bf4ef2dd5c136bd07296fff84efc4"
    source = "https://registry.npmjs.org/newrelic/-/newrelic-12.5.0.tgz"
    source-sha256 = "2a677c95ce634dccae627ee8dc06a30b106bf4ef2dd5c136bd07296fff84efc4"
    stacks = ["*"]
    uri = "https://registry.npmjs.org/newrelic/-/newrelic-12.5.0.tgz"
    version = "12.5.0"

    [[metadata.dependencies.licenses]]
      uri = "https://github.com/newrelic/node-newrelic/blob/HEAD/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:appdynamics:php-agent:11.1.0:*:*:*:*:*:*:*"]
    id = "new-relic-php"
    name = "New Relic PHP Agent"
    purl = "pkg:generic/newrelic-php-agent@11.1.0?arch=amd64"
    sha256 = "7e5ef259031ed8012b7ae17c4d5169392e01a5d9030bc93d061777ac3c625f92"
    source = "https://github.com/newrelic/newrelic-php-agent/archive/refs/tags/v11.1.0.14.tar.gz"
    source-sha256 = "287d2f0d9cdc851e30a9bcc45b44112ab8a8a7f06e1706809c27ac99352a3b15"
    stacks = ["*"]
    uri = "https://download.newrelic.com/php_agent/archive/11.1.0.14/newrelic-php5-11.1.0.14-linux.tar.gz"
    version = "11.1.0"

    [[metadata.dependencies.licenses]]
      uri = "https://docs.newrelic.com/docs/licenses/license-information"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:appdynamics:dotnet-agent:10.30.0:*:*:*:*:*:*:*"]
    id = "new-relic-dotnet"
    name = "New Relic Dotnet Agent"
    purl = "pkg:generic/newrelic-dotnet-agent@10.30.0?arch=amd64"
    sha256 = "5a93a52ec717363a2ca82d3d98f12ce947218392be4d41eb829427e6268c126e"
    source = "https://github.com/newrelic/newrelic-dotnet-agent/archive/refs/tags/v10.30.0.tar.gz"
    source-sha256 = "68dae375bc4f1c6b70ed41e3429f736af199f7620b2aeb9597714e23f52d3942"
    stacks = ["*"]
    uri = "https://download.newrelic.com/dot_net_agent/previous_releases/10.30.0/newrelic-dotnet-agent_10.30.0_amd64.tar.gz"
    version = "10.30.0"

    [[metadata.dependencies.licenses]]
      uri = "https://docs.newrelic.com/docs/licenses/license-information"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
