# Copyright 2018-2024 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes the New Relic Agent and configures it to connect to the service"
  homepage = "https://github.com/paketo-buildpacks/new-relic"
  id = "paketo-buildpacks/new-relic"
  keywords = ["new-relic", "agent", "apm", "java", "node.js", "php", "python", "dotnet"]
  name = "Paketo Buildpack for New Relic"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/new-relic/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/amd64/bin/helper", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "linux/arm64/bin/helper", "buildpack.toml", "resources/newrelic.js", "resources/newrelic.yml", "resources/newrelic.ini"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    description = "the SHA256 hash of the New Relic extensions archive"
    name = "BP_NEW_RELIC_EXT_SHA256"

  [[metadata.configurations]]
    build = true
    default = "0"
    description = "the number of directory components to strip from the New Relic extensions archive"
    name = "BP_NEW_RELIC_EXT_STRIP"

  [[metadata.configurations]]
    build = true
    description = "the download location of the New Relic extensions"
    name = "BP_NEW_RELIC_EXT_URI"

  [[metadata.configurations]]
    build = true
    description = "the version of the New Relic extensions"
    name = "BP_NEW_RELIC_EXT_VERSION"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:newrelic:java-agent:8.21.0:*:*:*:*:*:*:*"]
    id = "new-relic-java"
    name = "New Relic Java Agent"
    purl = "pkg:generic/newrelic-java-agent@8.21.0"
    sha256 = "64bb4c58101570658ad500df419dd35f4309417fea67b40cfce14a19d9013e11"
    source = "https://repo1.maven.org/maven2/com/newrelic/agent/java/newrelic-agent/8.21.0/newrelic-agent-8.21.0-sources.jar"
    source-sha256 = "f063c84485ea02469564d7af7e64c20e6628b6a789896438fb1a34a46fab6acb"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/newrelic/agent/java/newrelic-agent/8.21.0/newrelic-agent-8.21.0.jar"
    version = "8.21.0"

    [[metadata.dependencies.licenses]]
      uri = "https://newrelic.com/docs/java/java-agent-license"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:newrelic:nodejs-agent:12.14.0:*:*:*:*:*:*:*"]
    id = "new-relic-nodejs"
    name = "New Relic NodeJS Agent"
    purl = "pkg:generic/newrelic-nodejs-agent@12.14.0?arch=amd64"
    sha256 = "195031a0a42805df77d826b65d563840a39bfa86ee877d7ae3ad9122f9a259ac"
    source = "https://registry.npmjs.org/newrelic/-/newrelic-12.14.0.tgz"
    source-sha256 = "195031a0a42805df77d826b65d563840a39bfa86ee877d7ae3ad9122f9a259ac"
    stacks = ["*"]
    uri = "https://registry.npmjs.org/newrelic/-/newrelic-12.14.0.tgz"
    version = "12.14.0"

    [[metadata.dependencies.licenses]]
      uri = "https://github.com/newrelic/node-newrelic/blob/HEAD/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:appdynamics:php-agent:11.9.0:*:*:*:*:*:*:*"]
    id = "new-relic-php"
    name = "New Relic PHP Agent"
    purl = "pkg:generic/newrelic-php-agent@11.9.0?arch=amd64"
    sha256 = "c0bf6a5e61a76dce91d0bbce5c0f8c04e698c8fef6b63db236027c4c7b23e020"
    source = "https://github.com/newrelic/newrelic-php-agent/archive/refs/tags/v11.9.0.23.tar.gz"
    source-sha256 = "2a1481794a580dcd19a00ccd6b82ff56e1fd2acc31dae8d0306d2990afe5fe8e"
    stacks = ["*"]
    uri = "https://download.newrelic.com/php_agent/archive/11.9.0.23/newrelic-php5-11.9.0.23-linux.tar.gz"
    version = "11.9.0"

    [[metadata.dependencies.licenses]]
      uri = "https://docs.newrelic.com/docs/licenses/license-information"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:appdynamics:dotnet-agent:10.41.0:*:*:*:*:*:*:*"]
    id = "new-relic-dotnet"
    name = "New Relic Dotnet Agent"
    purl = "pkg:generic/newrelic-dotnet-agent@10.41.0?arch=amd64"
    sha256 = "d358c68d89bb2e9c453311cf2aca91947b8152459f7cb5bb735d76d9039a896a"
    source = "https://github.com/newrelic/newrelic-dotnet-agent/archive/refs/tags/v10.41.0.tar.gz"
    source-sha256 = "c8c755b6c7391131357e622303f28b4068e2b75f720e64797c0efcb8d7281b2a"
    stacks = ["*"]
    uri = "https://download.newrelic.com/dot_net_agent/previous_releases/10.41.0/newrelic-dotnet-agent_10.41.0_amd64.tar.gz"
    version = "10.41.0"

    [[metadata.dependencies.licenses]]
      uri = "https://docs.newrelic.com/docs/licenses/license-information"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
