# Copyright 2018-2024 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes the New Relic Agent and configures it to connect to the service"
  homepage = "https://github.com/paketo-buildpacks/new-relic"
  id = "paketo-buildpacks/new-relic"
  keywords = ["new-relic", "agent", "apm", "java", "node.js", "php", "python", "dotnet"]
  name = "Paketo Buildpack for New Relic"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/new-relic/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/amd64/bin/helper", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "linux/arm64/bin/helper", "buildpack.toml", "resources/newrelic.js", "resources/newrelic.yml", "resources/newrelic.ini"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    description = "the SHA256 hash of the New Relic extensions archive"
    name = "BP_NEW_RELIC_EXT_SHA256"

  [[metadata.configurations]]
    build = true
    default = "0"
    description = "the number of directory components to strip from the New Relic extensions archive"
    name = "BP_NEW_RELIC_EXT_STRIP"

  [[metadata.configurations]]
    build = true
    description = "the download location of the New Relic extensions"
    name = "BP_NEW_RELIC_EXT_URI"

  [[metadata.configurations]]
    build = true
    description = "the version of the New Relic extensions"
    name = "BP_NEW_RELIC_EXT_VERSION"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:newrelic:java-agent:8.16.0:*:*:*:*:*:*:*"]
    id = "new-relic-java"
    name = "New Relic Java Agent"
    purl = "pkg:generic/newrelic-java-agent@8.16.0"
    sha256 = "b7672c3a3b521daccb6d646b3d110539552b69a2de96277fba8dfe36e5413591"
    source = "https://repo1.maven.org/maven2/com/newrelic/agent/java/newrelic-agent/8.16.0/newrelic-agent-8.16.0-sources.jar"
    source-sha256 = "9817a6f289b89b80f559d9b7005cd81ad5452e2484d4b0c667549fb9b410cdbb"
    stacks = ["*"]
    uri = "https://repo1.maven.org/maven2/com/newrelic/agent/java/newrelic-agent/8.16.0/newrelic-agent-8.16.0.jar"
    version = "8.16.0"

    [[metadata.dependencies.licenses]]
      uri = "https://newrelic.com/docs/java/java-agent-license"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:newrelic:nodejs-agent:12.7.0:*:*:*:*:*:*:*"]
    id = "new-relic-nodejs"
    name = "New Relic NodeJS Agent"
    purl = "pkg:generic/newrelic-nodejs-agent@12.7.0?arch=amd64"
    sha256 = "9339608da8db43e895f1964f4f63568225c4319579b7c653db79d1e09d221258"
    source = "https://registry.npmjs.org/newrelic/-/newrelic-12.7.0.tgz"
    source-sha256 = "9339608da8db43e895f1964f4f63568225c4319579b7c653db79d1e09d221258"
    stacks = ["*"]
    uri = "https://registry.npmjs.org/newrelic/-/newrelic-12.7.0.tgz"
    version = "12.7.0"

    [[metadata.dependencies.licenses]]
      uri = "https://github.com/newrelic/node-newrelic/blob/HEAD/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:appdynamics:php-agent:11.3.0:*:*:*:*:*:*:*"]
    id = "new-relic-php"
    name = "New Relic PHP Agent"
    purl = "pkg:generic/newrelic-php-agent@11.3.0?arch=amd64"
    sha256 = "1cf1a6b2e93f327d47cb9ca5877c4b8ef939ec3bb69f9de0e487668dca4d3ae2"
    source = "https://github.com/newrelic/newrelic-php-agent/archive/refs/tags/v11.3.0.16.tar.gz"
    source-sha256 = "59aecc76595da955f412f9fc0a08f3c5368682c406f69fb86ee932304f817740"
    stacks = ["*"]
    uri = "https://download.newrelic.com/php_agent/archive/11.3.0.16/newrelic-php5-11.3.0.16-linux.tar.gz"
    version = "11.3.0"

    [[metadata.dependencies.licenses]]
      uri = "https://docs.newrelic.com/docs/licenses/license-information"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:appdynamics:dotnet-agent:10.34.1:*:*:*:*:*:*:*"]
    id = "new-relic-dotnet"
    name = "New Relic Dotnet Agent"
    purl = "pkg:generic/newrelic-dotnet-agent@10.34.1?arch=amd64"
    sha256 = "86c126a09c232931a7523cedd125e20c11d105547c5ed5c4cb246f7a4937f210"
    source = "https://github.com/newrelic/newrelic-dotnet-agent/archive/refs/tags/v10.34.1.tar.gz"
    source-sha256 = "5e8600b904c072486c74731200c9b08fde4857f1239f6c5e17d669e0a6680047"
    stacks = ["*"]
    uri = "https://download.newrelic.com/dot_net_agent/previous_releases/10.34.1/newrelic-dotnet-agent_10.34.1_amd64.tar.gz"
    version = "10.34.1"

    [[metadata.dependencies.licenses]]
      uri = "https://docs.newrelic.com/docs/licenses/license-information"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
