# Copyright 2018-2022 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes the New Relic Agent and configures it to connect to the service"
  homepage = "https://github.com/paketo-buildpacks/new-relic"
  id = "paketo-buildpacks/new-relic"
  keywords = ["new-relic", "agent", "apm", "java", "node.js", "php", "python", "dotnet"]
  name = "Paketo Buildpack for New Relic"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/new-relic/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/helper", "bin/main", "buildpack.toml", "resources/newrelic.js", "resources/newrelic.yml", "resources/newrelic.ini"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    description = "the SHA256 hash of the New Relic extensions archive"
    name = "BP_NEW_RELIC_EXT_SHA256"

  [[metadata.configurations]]
    build = true
    default = "0"
    description = "the number of directory components to strip from the New Relic extensions archive"
    name = "BP_NEW_RELIC_EXT_STRIP"

  [[metadata.configurations]]
    build = true
    description = "the download location of the New Relic extensions"
    name = "BP_NEW_RELIC_EXT_URI"

  [[metadata.configurations]]
    build = true
    description = "the version of the New Relic extensions"
    name = "BP_NEW_RELIC_EXT_VERSION"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:newrelic:java-agent:8.11.0:*:*:*:*:*:*:*"]
    id = "new-relic-java"
    name = "New Relic Java Agent"
    purl = "pkg:generic/newrelic-java-agent@8.11.0?arch=amd64"
    sha256 = "48f325d244f9380fa23d0c322921f9b2e0d6fb095875d84f2b007db5ddef0b60"
    source = "https://repo1.maven.org/maven2/com/newrelic/agent/java/newrelic-agent/8.11.0/newrelic-agent-8.11.0-sources.jar"
    source-sha256 = "0c5280f2b7797a4be6a49b7277afb2b6114e064fc87283ff6cee7f7ad6bfe155"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://repo1.maven.org/maven2/com/newrelic/agent/java/newrelic-agent/8.11.0/newrelic-agent-8.11.0.jar"
    version = "8.11.0"

    [[metadata.dependencies.licenses]]
      uri = "https://newrelic.com/docs/java/java-agent-license"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:newrelic:nodejs-agent:11.15.0:*:*:*:*:*:*:*"]
    id = "new-relic-nodejs"
    name = "New Relic NodeJS Agent"
    purl = "pkg:generic/newrelic-nodejs-agent@11.15.0?arch=amd64"
    sha256 = "d0de16aa4aa1cad2d573fac06098a7f28cc2c7b0d884eb2fd4ed46a09a154bbe"
    source = "https://registry.npmjs.org/newrelic/-/newrelic-11.15.0.tgz"
    source-sha256 = "d0de16aa4aa1cad2d573fac06098a7f28cc2c7b0d884eb2fd4ed46a09a154bbe"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://registry.npmjs.org/newrelic/-/newrelic-11.15.0.tgz"
    version = "11.15.0"

    [[metadata.dependencies.licenses]]
      uri = "https://github.com/newrelic/node-newrelic/blob/HEAD/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:appdynamics:php-agent:10.19.0:*:*:*:*:*:*:*"]
    id = "new-relic-php"
    name = "New Relic PHP Agent"
    purl = "pkg:generic/newrelic-php-agent@10.19.0?arch=amd64"
    sha256 = "0062d06ed410ec19931b214b5d187c132c836dbbddfd357458ddf3f7615c02e9"
    source = "https://github.com/newrelic/newrelic-php-agent/archive/refs/tags/v10.19.0.9.tar.gz"
    source-sha256 = "468244261ce5e7886834774e75493493a35d348a7659436fddbdc74fa769fc66"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://download.newrelic.com/php_agent/archive/10.19.0.9/newrelic-php5-10.19.0.9-linux.tar.gz"
    version = "10.19.0"

    [[metadata.dependencies.licenses]]
      uri = "https://docs.newrelic.com/docs/licenses/license-information"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:appdynamics:dotnet-agent:10.23.1:*:*:*:*:*:*:*"]
    id = "new-relic-dotnet"
    name = "New Relic Dotnet Agent"
    purl = "pkg:generic/newrelic-dotnet-agent@10.23.1?arch=amd64"
    sha256 = "a35320228dcd48a8a33de7fb719a7b1d676e96f29a3551416a62fcfdf423c38c"
    source = "https://github.com/newrelic/newrelic-dotnet-agent/archive/refs/tags/v10.23.1.tar.gz"
    source-sha256 = "9316dae3c5067888a1a7ab09b6605278eb99649b980e1c35a4f1beca00bcf5bf"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://download.newrelic.com/dot_net_agent/previous_releases/10.23.1/newrelic-dotnet-agent_10.23.1_amd64.tar.gz"
    version = "10.23.1"

    [[metadata.dependencies.licenses]]
      uri = "https://docs.newrelic.com/docs/licenses/license-information"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"
